# # development build with npm start (slow and bulky)
# # Stage 1: Build docker image of react app
# FROM node:latest as build

# # Create an app directory to hold the application code inside the image
# WORKDIR /src/app

# # Copy app dependencies (package.json, package-lock.json, tsconfig.json, etc)
# COPY package*.json ./

# # Install app dependencies
# RUN npm install --silent


# # Copy the rest of the application code
# COPY . .

# EXPOSE 3001

# CMD ["npm", "start"]

# docker run -d -p 127.0.0.1:3001:3001  --env-file ../.env cs3219-frontend-v1

# dev build v2
# Stage 1: Build docker image of react app
FROM node:alpine as build

# Create an app directory to hold the application code inside the image
WORKDIR /src/app

# Copy app dependencies (package.json, package-lock.json, tsconfig.json, etc)
COPY package*.json ./

# Install app dependencies
RUN npm install --silent


# Copy the rest of the application code
COPY . .

ARG REACT_APP_USER_SVC
ENV REACT_APP_USER_SVC=$REACT_APP_USER_SVC
ARG REACT_APP_QNS_SVC
ENV REACT_APP_QNS_SVC=$REACT_APP_QNS_SVC
ARG REACT_APP_MTC_SVC
ENV REACT_APP_MTC_SVC=$REACT_APP_MTC_SVC
ARG REACT_APP_USR_SVC_HIST
ENV REACT_APP_USR_SVC_HIST=$REACT_APP_USR_SVC_HIST
ARG REACT_APP_USR_SVC_AUTH
ENV REACT_APP_USR_SVC_AUTH=$REACT_APP_USR_SVC_AUTH

# Build the app
RUN npm run build

RUN npm i -g serve

EXPOSE 3001

CMD ["serve", "-s", "build","-l","3001"]