steps:
# build the user service
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t',
  'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g06-user-service/cs3219-g06-user-service-image:$COMMIT_SHA', 
  '-f', './user-service/Dockerfile','./user-service']
# push user service container to Artifact Registry
- name: gcr.io/cloud-builders/docker
  args: ['push', 
  'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g06-user-service/cs3219-g06-user-service-image:$COMMIT_SHA']
  
# deploy container to cloud run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ['run', 'deploy', 
  'user-service', '--image', 
  'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g06-user-service/cs3219-g06-user-service-image:$COMMIT_SHA', 
  '--region', 'asia-northeast1', '--allow-unauthenticated']

options:
  serviceAccount: $_SERVICE_ACCOUNT
# timeout: 1200s
# images:
# - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
# test